# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-19 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MC_REQUEST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField()),
                ('pending', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MC_RESULT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_string', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='MC_SCHOOL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('total_number_of_students', models.IntegerField()),
                ('identified_student_population', models.IntegerField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mealscountserver.MC_REQUEST')),
            ],
        ),
        migrations.AddField(
            model_name='mc_request',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mealscountserver.MC_RESULT'),
        ),
    ]
