# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-20 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealscountserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_request',
            name='email',
            field=models.CharField(default='rishavdas@hotmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
