# Generated by Django 2.0.5 on 2018-06-03 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealscountserver', '0003_auto_20180531_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districtadmin',
            name='district',
        ),
        migrations.RemoveField(
            model_name='districtadmin',
            name='full_name',
        ),
    ]
