# Generated by Django 2.0.5 on 2018-06-03 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mealscountserver', '0004_auto_20180603_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtadmin',
            name='district',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='mealscountserver.District'),
        ),
    ]
