# Generated by Django 2.0.5 on 2018-06-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealscountserver', '0006_auto_20180605_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='district_name',
            field=models.CharField(max_length=200),
        ),
    ]
