# Generated by Django 2.0.5 on 2018-06-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealscountserver', '0007_auto_20180605_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='district_qualifies_for_performance_based_cash_assistance',
            field=models.BooleanField(default=False),
        ),
    ]
